### ISSUE TITLE
截至

### ISSUE THREAD

**Issue by imogenepeng** [consideration-ak/pigaiwang-toolkit#1]
大大 已经截止得作业还有办法修改吗🙏

**Comment by consideration-ak** [comment]
这个真没办法, 我都试过的, 服务器会拒绝请求, 最好用的方法还是跟你们老师寻求解决方案hhh

**Comment by imogenepeng** [comment]
> 这个真没办法，我都试过的，服务器会拒绝请求，最好用的方法还是跟你们老师寻求解决方案hhh

好吧 谢谢你！
